name: FriendSystem
version: '1.0-SNAPSHOT'
main: me.yinzuro.friendSystem.FriendSystem
api-version: '1.21'
commands:
  friend:
    description: Manage your friends
    aliases: [friends]
  message:
    description: Message a friend
    aliases: [msg]
  respond:
    description: Respond to a friend
    aliases: [r]